### ISSUE TITLE
[質問]: WaterFallサーバーは必要なのか？

### ISSUE THREAD

**Issue by hirotask** [koryuServer/SkillMaster#289]
### 質問内容

現在、Paperサーバー１つとWaterfallサーバー１つを用いてサーバーを構成している。

しかし、WaterFallサーバーはプロキシサーバーであり、Paperサーバーが１つの場合存在する意味がほぼない。
したがって、WaterFallサーバーは必要なのかどうか確認したい。

**Comment by Koryu25** [comment]
前から思ってたけど、必要ないね

**Comment by hirotask** [comment]
おっけー
じゃあ開発環境・ステージング環境・本番環境のコンテナにもWaterfallは含めなくてもOK？

**Comment by Koryu25** [comment]
おっけーだよ
